project:
  type: website

website:
  title: "Bomenluisteraar: treetalkers"
  navbar:
    left:
      - href: index.qmd
        text: "Bomenluisteraar: treetalkers"
      - href: battery.qmd
        text: "Batterijspanning"
      - href: about.qmd
        text: "Over deze website"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true