project:
  type: website

website:
  title: "Bomenluisteraar: treetalkers"
  navbar:
    left:
      - href: index.qmd
        text: "Bomenluisteraar: treetalkers"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true